-- Optional: launch Brave with the Matrix theme applied on a fresh start.
-- Unbind first if SUPER+SHIFT+B is already taken.
--
-- hl.unbind("SUPER + SHIFT + B")
-- o.bind("SUPER + SHIFT + B", "Brave", os.getenv("HOME") .. "/.local/bin/omarchy-brave-matrix")
