;;; omarchy-matrix-theme.el --- CRT phosphor theme matching Omarchy Matrix -*- lexical-binding: t; -*-

;; Author: Justin Andrusk
;; Version: 1.0
;; Package-Requires: ((emacs "29.1"))
;; Keywords: faces, theme

;;; Commentary:
;;
;; Dark digital-rain theme whose palette is taken from the Omarchy
;; Matrix desktop theme (~/.config/omarchy/themes/matrix/colors.toml).
;; Syntax roles follow the generated Helix / VS Code mappings so Emacs
;; matches the rest of the desktop.

;;; Code:

(deftheme omarchy-matrix
  "Dark CRT phosphor theme matching the Omarchy Matrix desktop."
  :background-mode 'dark
  :kind 'color-scheme)

(let* ((class '((class color) (min-colors 89)))
       ;; Core (colors.toml)
       (bg        "#050a05")
       (bg-dark   "#030603")
       (bg-darker "#010201")
       (bg-alt    "#0d160d")
       (fg        "#9ae89a")
       (fg-dark   "#3d7a48")
       (fg-light  "#c4f5c4")
       (fg-bright "#e8ffe8")
       (accent    "#00ff41")
       (select    "#0a3d14")
       (muted     "#1f5c28")
       ;; ANSI / semantic
       (red       "#e20400")
       (yellow    "#c6e547")
       (orange    "#e36a13")
       (green     "#00d632")
       (cyan      "#33ff88")
       (blue      "#3a74d2")
       (magenta   "#6b37b3")
       (brown     "#3d6b2f")
       (bred      "#ff4a45")
       (byellow   "#e8ff6a")
       (bgreen    "#5cff7a")
       (bcyan     "#7dffb0")
       (bblue     "#6a9eff")
       (bmagenta  "#9a6adf")
       ;; Derived (still in-family; used where the raw hue is too dim)
       (comment   "#3d7a48")
       (keyword   "#9a6adf")
       (fn        "#6a9eff")
       (type      "#c6e547")
       (str       "#00d632")
       (const     "#e36a13")
       (builtin   "#33ff88")
       (cursor-c  "#00ff41"))
  (custom-theme-set-faces
   'omarchy-matrix

   ;; --- Core ----------------------------------------------------------
   `(default ((,class :background ,bg :foreground ,fg)))
   `(cursor ((,class :background ,cursor-c :foreground ,bg)))
   `(fringe ((,class :background ,bg :foreground ,muted)))
   `(vertical-border ((,class :foreground ,muted)))
   `(window-divider ((,class :foreground ,muted)))
   `(window-divider-first-pixel ((,class :foreground ,muted)))
   `(window-divider-last-pixel ((,class :foreground ,muted)))
   `(internal-border ((,class :foreground ,muted)))
   `(scroll-bar ((,class :background ,bg :foreground ,muted)))
   `(border ((,class :foreground ,muted)))
   `(shadow ((,class :foreground ,fg-dark)))
   `(link ((,class :foreground ,blue :underline t)))
   `(link-visited ((,class :foreground ,bmagenta :underline t)))
   `(button ((,class :foreground ,accent :underline t)))
   `(highlight ((,class :background ,select :foreground ,fg-bright)))
   `(hl-line ((,class :background ,bg-alt :extend t)))
   `(region ((,class :background ,select :foreground ,fg-bright :extend t)))
   `(secondary-selection ((,class :background ,muted :foreground ,fg-bright :extend t)))
   `(trailing-whitespace ((,class :background ,red)))
   `(escape-glyph ((,class :foreground ,cyan)))
   `(nobreak-space ((,class :foreground ,cyan :underline t)))
   `(homoglyph ((,class :foreground ,yellow)))
   `(error ((,class :foreground ,red :weight bold)))
   `(warning ((,class :foreground ,yellow :weight bold)))
   `(success ((,class :foreground ,green :weight bold)))
   `(tooltip ((,class :background ,bg-alt :foreground ,fg)))
   `(help-key-binding ((,class :background ,bg-alt :foreground ,accent
                               :box (:line-width 1 :color ,muted))))

   ;; --- Mode line / header / tabs ------------------------------------
   `(mode-line
     ((,class :background ,select :foreground ,accent :weight bold
              :box (:line-width 1 :color ,accent))))
   `(mode-line-active ((,class :inherit mode-line)))
   `(mode-line-inactive
     ((,class :background ,bg-darker :foreground ,fg-dark
              :box (:line-width 1 :color ,muted))))
   `(mode-line-highlight ((,class :foreground ,fg-bright :background ,muted)))
   `(mode-line-buffer-id ((,class :foreground ,accent :weight bold)))
   `(mode-line-emphasis ((,class :foreground ,fg-bright :weight bold)))
   `(header-line
     ((,class :background ,bg-dark :foreground ,fg-light
              :box (:line-width 1 :color ,muted))))
   `(tab-bar ((,class :background ,bg-dark :foreground ,fg-dark)))
   `(tab-bar-tab
     ((,class :background ,bg :foreground ,accent :weight bold
              :box (:line-width 1 :color ,accent))))
   `(tab-bar-tab-inactive ((,class :background ,bg-darker :foreground ,fg-dark)))
   `(tab-line ((,class :background ,bg-darker :foreground ,fg-dark)))
   `(tab-line-tab-current ((,class :background ,bg :foreground ,accent :weight bold)))
   `(tab-line-tab-inactive ((,class :background ,bg-darker :foreground ,fg-dark)))
   `(tab-line-highlight ((,class :background ,select :foreground ,fg-bright)))

   ;; --- Line numbers / fill / paren ----------------------------------
   `(line-number ((,class :background ,bg :foreground ,muted)))
   `(line-number-current-line ((,class :background ,bg-alt :foreground ,accent :weight bold)))
   `(line-number-major-tick ((,class :foreground ,fg-dark)))
   `(line-number-minor-tick ((,class :foreground ,muted)))
   `(fill-column-indicator ((,class :foreground ,muted)))
   `(show-paren-match ((,class :background ,select :foreground ,accent :weight bold)))
   `(show-paren-match-expression ((,class :background ,bg-alt)))
   `(show-paren-mismatch ((,class :background ,red :foreground ,fg-bright :weight bold)))
   `(sp-show-pair-match-face ((,class :inherit show-paren-match)))
   `(sp-show-pair-mismatch-face ((,class :inherit show-paren-mismatch)))

   ;; --- Search --------------------------------------------------------
   `(isearch ((,class :background ,yellow :foreground ,bg :weight bold)))
   `(isearch-fail ((,class :background ,red :foreground ,fg-bright)))
   `(lazy-highlight ((,class :background ,select :foreground ,fg-light)))
   `(match ((,class :background ,select :foreground ,accent)))
   `(query-replace ((,class :inherit isearch)))
   `(isearch-group-1 ((,class :background ,cyan :foreground ,bg)))
   `(isearch-group-2 ((,class :background ,bblue :foreground ,bg)))

   ;; --- Minibuffer / completions -------------------------------------
   `(minibuffer-prompt ((,class :foreground ,accent :weight bold)))
   `(completions-annotations ((,class :foreground ,fg-dark :slant italic)))
   `(completions-common-part ((,class :foreground ,accent :weight bold)))
   `(completions-first-difference ((,class :foreground ,yellow)))
   `(completions-highlight ((,class :background ,select :foreground ,fg-bright)))
   `(icomplete-first-match ((,class :foreground ,accent :weight bold)))

   `(vertico-current ((,class :background ,select :foreground ,fg-bright :extend t :weight bold)))
   `(vertico-group-title ((,class :foreground ,accent :slant italic :weight bold)))
   `(vertico-group-separator ((,class :foreground ,muted :strike-through t)))
   `(vertico-multiline ((,class :foreground ,fg-dark)))

   `(corfu-default ((,class :background ,bg-alt :foreground ,fg)))
   `(corfu-current ((,class :background ,select :foreground ,fg-bright :weight bold)))
   `(corfu-bar ((,class :background ,accent)))
   `(corfu-border ((,class :background ,accent)))
   `(corfu-annotations ((,class :foreground ,fg-dark :slant italic)))
   `(corfu-deprecated ((,class :foreground ,fg-dark :strike-through t)))
   `(corfu-echo ((,class :foreground ,fg-light)))
   `(corfu-popupinfo ((,class :background ,bg-alt :foreground ,fg)))

   `(orderless-match-face-0 ((,class :foreground ,accent :weight bold)))
   `(orderless-match-face-1 ((,class :foreground ,cyan :weight bold)))
   `(orderless-match-face-2 ((,class :foreground ,yellow :weight bold)))
   `(orderless-match-face-3 ((,class :foreground ,bblue :weight bold)))

   ;; --- Font lock / treesit ------------------------------------------
   `(font-lock-comment-face ((,class :foreground ,comment :slant italic)))
   `(font-lock-comment-delimiter-face ((,class :foreground ,muted :slant italic)))
   `(font-lock-doc-face ((,class :foreground ,brown :slant italic)))
   `(font-lock-doc-markup-face ((,class :foreground ,cyan)))
   `(font-lock-string-face ((,class :foreground ,str)))
   `(font-lock-keyword-face ((,class :foreground ,keyword :weight bold)))
   `(font-lock-builtin-face ((,class :foreground ,builtin)))
   `(font-lock-type-face ((,class :foreground ,type)))
   `(font-lock-function-name-face ((,class :foreground ,fn)))
   `(font-lock-function-call-face ((,class :foreground ,fn)))
   `(font-lock-variable-name-face ((,class :foreground ,fg)))
   `(font-lock-variable-use-face ((,class :foreground ,fg)))
   `(font-lock-constant-face ((,class :foreground ,const)))
   `(font-lock-preprocessor-face ((,class :foreground ,bmagenta)))
   `(font-lock-warning-face ((,class :foreground ,yellow :weight bold)))
   `(font-lock-negation-char-face ((,class :foreground ,red :weight bold)))
   `(font-lock-regexp-grouping-backslash ((,class :foreground ,bmagenta :weight bold)))
   `(font-lock-regexp-grouping-construct ((,class :foreground ,cyan :weight bold)))
   `(font-lock-number-face ((,class :foreground ,const)))
   `(font-lock-operator-face ((,class :foreground ,bblue)))
   `(font-lock-escape-face ((,class :foreground ,bmagenta)))
   `(font-lock-property-name-face ((,class :foreground ,cyan)))
   `(font-lock-property-use-face ((,class :foreground ,cyan)))
   `(font-lock-punctuation-face ((,class :foreground ,muted)))
   `(font-lock-bracket-face ((,class :foreground ,fg-light)))
   `(font-lock-delimiter-face ((,class :foreground ,muted)))
   `(font-lock-misc-punctuation-face ((,class :foreground ,muted)))

   ;; --- Diff / smerge / ediff ----------------------------------------
   `(diff-added ((,class :background "#062411" :foreground ,green :extend t)))
   `(diff-removed ((,class :background "#2a0604" :foreground ,bred :extend t)))
   `(diff-changed ((,class :background "#1a1804" :foreground ,yellow :extend t)))
   `(diff-refine-added ((,class :background "#0a3d14" :foreground ,bgreen :weight bold)))
   `(diff-refine-removed ((,class :background "#4a0c08" :foreground ,bred :weight bold)))
   `(diff-refine-changed ((,class :background "#3a3808" :foreground ,byellow)))
   `(diff-header ((,class :foreground ,fg-light :background ,bg-alt :extend t)))
   `(diff-file-header ((,class :foreground ,accent :background ,bg-alt :weight bold :extend t)))
   `(diff-hunk-header ((,class :foreground ,fn :background ,bg-alt :extend t)))
   `(diff-function ((,class :foreground ,fn)))
   `(diff-indicator-added ((,class :foreground ,green)))
   `(diff-indicator-removed ((,class :foreground ,red)))
   `(diff-indicator-changed ((,class :foreground ,yellow)))
   `(smerge-upper ((,class :background "#2a0604" :extend t)))
   `(smerge-lower ((,class :background "#062411" :extend t)))
   `(smerge-base ((,class :background "#1a1804" :extend t)))
   `(smerge-markers ((,class :background ,bg-alt :foreground ,fg-dark :extend t)))
   `(smerge-refined-added ((,class :background ,select :foreground ,bgreen)))
   `(smerge-refined-removed ((,class :background "#4a0c08" :foreground ,bred)))

   ;; --- Magit ---------------------------------------------------------
   `(magit-section-heading ((,class :foreground ,accent :weight bold)))
   `(magit-section-highlight ((,class :background ,bg-alt :extend t)))
   `(magit-section-heading-selection ((,class :background ,select :foreground ,fg-bright)))
   `(magit-section-secondary-heading ((,class :foreground ,fg-light :weight bold)))
   `(magit-hash ((,class :foreground ,fg-dark)))
   `(magit-dimmed ((,class :foreground ,fg-dark)))
   `(magit-tag ((,class :foreground ,yellow)))
   `(magit-filename ((,class :foreground ,fg)))
   `(magit-branch-local ((,class :foreground ,cyan)))
   `(magit-branch-current ((,class :foreground ,accent :weight bold :box (:line-width 1 :color ,accent))))
   `(magit-branch-remote ((,class :foreground ,green)))
   `(magit-branch-remote-head ((,class :foreground ,bgreen)))
   `(magit-branch-upstream ((,class :foreground ,blue)))
   `(magit-head ((,class :foreground ,accent)))
   `(magit-refname ((,class :foreground ,fg-dark)))
   `(magit-keyword ((,class :foreground ,keyword)))
   `(magit-keyword-squash ((,class :foreground ,red :weight bold)))
   `(magit-signature-good ((,class :foreground ,green)))
   `(magit-signature-bad ((,class :foreground ,red :weight bold)))
   `(magit-signature-untrusted ((,class :foreground ,yellow)))
   `(magit-signature-expired ((,class :foreground ,orange)))
   `(magit-signature-error ((,class :foreground ,red)))
   `(magit-diff-added ((,class :background "#062411" :foreground ,green :extend t)))
   `(magit-diff-added-highlight ((,class :background "#0a3d14" :foreground ,bgreen :extend t)))
   `(magit-diff-removed ((,class :background "#2a0604" :foreground ,bred :extend t)))
   `(magit-diff-removed-highlight ((,class :background "#4a0c08" :foreground ,bred :extend t)))
   `(magit-diff-context ((,class :foreground ,fg-dark :extend t)))
   `(magit-diff-context-highlight ((,class :background ,bg-alt :foreground ,fg :extend t)))
   `(magit-diff-hunk-heading ((,class :background ,bg-alt :foreground ,fg-dark :extend t)))
   `(magit-diff-hunk-heading-highlight ((,class :background ,select :foreground ,fg-light :extend t :weight bold)))
   `(magit-diff-hunk-heading-selection ((,class :background ,select :foreground ,accent :extend t)))
   `(magit-diff-file-heading ((,class :foreground ,fg-light :weight bold)))
   `(magit-diff-file-heading-highlight ((,class :background ,bg-alt :foreground ,accent :weight bold :extend t)))
   `(magit-diff-file-heading-selection ((,class :background ,select :foreground ,fg-bright)))
   `(magit-diffstat-added ((,class :foreground ,green)))
   `(magit-diffstat-removed ((,class :foreground ,red)))
   `(magit-log-author ((,class :foreground ,orange)))
   `(magit-log-date ((,class :foreground ,fg-dark)))
   `(magit-log-graph ((,class :foreground ,muted)))
   `(magit-process-ok ((,class :foreground ,green :weight bold)))
   `(magit-process-ng ((,class :foreground ,red :weight bold)))
   `(magit-reflog-commit ((,class :foreground ,green)))
   `(magit-reflog-amend ((,class :foreground ,bmagenta)))
   `(magit-reflog-merge ((,class :foreground ,green)))
   `(magit-reflog-checkout ((,class :foreground ,blue)))
   `(magit-reflog-reset ((,class :foreground ,red)))
   `(magit-reflog-rebase ((,class :foreground ,bmagenta)))
   `(magit-reflog-cherry-pick ((,class :foreground ,green)))
   `(magit-reflog-remote ((,class :foreground ,cyan)))
   `(magit-reflog-other ((,class :foreground ,cyan)))
   `(git-commit-summary ((,class :foreground ,fg-light :weight bold)))
   `(git-commit-overlong-summary ((,class :foreground ,red)))
   `(git-commit-nonempty-second-line ((,class :foreground ,yellow)))
   `(git-commit-comment-heading ((,class :foreground ,accent)))
   `(git-commit-comment-branch-local ((,class :foreground ,cyan)))
   `(git-commit-comment-branch-remote ((,class :foreground ,green)))
   `(git-commit-comment-file ((,class :foreground ,fg)))
   `(git-commit-comment-action ((,class :foreground ,keyword)))

   ;; --- Org -----------------------------------------------------------
   `(org-default ((,class :foreground ,fg)))
   `(org-document-title ((,class :foreground ,accent :weight bold :height 1.3)))
   `(org-document-info ((,class :foreground ,fg-light)))
   `(org-document-info-keyword ((,class :foreground ,fg-dark)))
   `(org-meta-line ((,class :foreground ,fg-dark :slant italic)))
   `(org-block ((,class :background ,bg-alt :foreground ,fg :extend t)))
   `(org-block-begin-line ((,class :background ,bg-darker :foreground ,muted :extend t :slant italic)))
   `(org-block-end-line ((,class :inherit org-block-begin-line)))
   `(org-code ((,class :foreground ,cyan :background ,bg-alt)))
   `(org-verbatim ((,class :foreground ,cyan :background ,bg-alt)))
   `(org-hide ((,class :foreground ,bg)))
   `(org-indent ((,class :inherit (fixed-pitch org-hide))))
   `(org-drawer ((,class :foreground ,fg-dark)))
   `(org-special-keyword ((,class :foreground ,fg-dark)))
   `(org-property-value ((,class :foreground ,fg-light)))
   `(org-tag ((,class :foreground ,cyan :weight normal)))
   `(org-date ((,class :foreground ,blue :underline t)))
   `(org-date-selected ((,class :foreground ,accent :inverse-video t)))
   `(org-table ((,class :foreground ,fg-light :background ,bg-alt)))
   `(org-formula ((,class :foreground ,orange)))
   `(org-todo ((,class :foreground ,red :weight bold)))
   `(org-done ((,class :foreground ,green :weight bold)))
   `(org-headline-done ((,class :foreground ,fg-dark)))
   `(org-headline-todo ((,class :foreground ,fg)))
   `(org-priority ((,class :foreground ,orange)))
   `(org-checkbox ((,class :foreground ,accent :weight bold)))
   `(org-checkbox-statistics-todo ((,class :foreground ,yellow)))
   `(org-checkbox-statistics-done ((,class :foreground ,green)))
   `(org-ellipsis ((,class :foreground ,muted :underline nil)))
   `(org-level-1 ((,class :foreground ,accent :weight bold :height 1.2)))
   `(org-level-2 ((,class :foreground ,bgreen :weight bold :height 1.12)))
   `(org-level-3 ((,class :foreground ,yellow :weight bold :height 1.06)))
   `(org-level-4 ((,class :foreground ,cyan :weight bold)))
   `(org-level-5 ((,class :foreground ,bblue :weight bold)))
   `(org-level-6 ((,class :foreground ,bmagenta :weight bold)))
   `(org-level-7 ((,class :foreground ,fg-light :weight bold)))
   `(org-level-8 ((,class :foreground ,fg-dark :weight bold)))
   `(org-link ((,class :foreground ,blue :underline t)))
   `(org-footnote ((,class :foreground ,bblue :underline t)))
   `(org-quote ((,class :inherit org-block :slant italic :foreground ,fg-light)))
   `(org-verse ((,class :inherit org-block :slant italic)))
   `(org-list-dt ((,class :foreground ,accent :weight bold)))
   `(org-scheduled ((,class :foreground ,green)))
   `(org-scheduled-today ((,class :foreground ,accent :weight bold)))
   `(org-scheduled-previously ((,class :foreground ,orange)))
   `(org-upcoming-deadline ((,class :foreground ,yellow)))
   `(org-warning ((,class :foreground ,red :weight bold)))
   `(org-deadline-announce ((,class :foreground ,red)))
   `(org-agenda-structure ((,class :foreground ,accent :weight bold)))
   `(org-agenda-date ((,class :foreground ,fn)))
   `(org-agenda-date-today ((,class :foreground ,accent :weight bold :underline t)))
   `(org-agenda-date-weekend ((,class :foreground ,fg-dark)))
   `(org-agenda-done ((,class :foreground ,green)))
   `(org-agenda-current-time ((,class :foreground ,yellow)))
   `(org-time-grid ((,class :foreground ,muted)))
   `(org-habit-clear-face ((,class :background ,blue :foreground ,fg-bright)))
   `(org-habit-clear-future-face ((,class :background "#1a3058" :foreground ,fg)))
   `(org-habit-ready-face ((,class :background ,green :foreground ,bg)))
   `(org-habit-ready-future-face ((,class :background ,select :foreground ,green)))
   `(org-habit-alert-face ((,class :background ,yellow :foreground ,bg)))
   `(org-habit-alert-future-face ((,class :background "#3a3808" :foreground ,yellow)))
   `(org-habit-overdue-face ((,class :background ,red :foreground ,fg-bright)))
   `(org-habit-overdue-future-face ((,class :background "#4a0c08" :foreground ,bred)))
   `(org-roam-header-line ((,class :foreground ,accent :weight bold)))
   `(org-roam-title ((,class :foreground ,accent :weight bold)))
   `(org-roam-olp ((,class :foreground ,fg-dark)))
   `(org-dispatcher-highlight ((,class :background ,select :foreground ,accent :weight bold)))

   ;; --- Elfeed --------------------------------------------------------
   `(elfeed-search-date-face ((,class :foreground ,fg-dark)))
   `(elfeed-search-title-face ((,class :foreground ,fg-dark)))
   `(elfeed-search-unread-title-face ((,class :foreground ,fg :weight bold)))
   `(elfeed-search-feed-face ((,class :foreground ,cyan)))
   `(elfeed-search-tag-face ((,class :foreground ,green)))
   `(elfeed-search-unread-count-face ((,class :foreground ,accent :weight bold)))
   `(elfeed-search-filter-face ((,class :foreground ,accent)))
   `(elfeed-search-last-update-face ((,class :foreground ,fg-dark)))
   `(elfeed-search-unstarred-title-face ((,class :foreground ,fg)))
   `(elfeed-search-starred-title-face ((,class :foreground ,yellow :weight bold)))
   `(elfeed-search-marked-face ((,class :background ,select :foreground ,accent)))
   `(elfeed-show-title-face ((,class :foreground ,accent :weight bold :height 1.2)))
   `(elfeed-show-author-face ((,class :foreground ,orange)))
   `(elfeed-show-date-face ((,class :foreground ,fg-dark)))
   `(elfeed-show-feed-face ((,class :foreground ,cyan)))
   `(elfeed-show-tag-face ((,class :foreground ,green)))
   `(message-header-name ((,class :foreground ,accent)))
   `(message-header-subject ((,class :foreground ,fg-light :weight bold)))
   `(message-header-to ((,class :foreground ,cyan)))
   `(message-header-cc ((,class :foreground ,fn)))
   `(message-header-other ((,class :foreground ,fg)))
   `(message-header-xheader ((,class :foreground ,fg-dark)))
   `(message-separator ((,class :foreground ,muted)))
   `(message-cited-text-1 ((,class :foreground ,green :slant italic)))
   `(message-cited-text-2 ((,class :foreground ,cyan :slant italic)))
   `(message-cited-text-3 ((,class :foreground ,yellow :slant italic)))
   `(message-cited-text-4 ((,class :foreground ,fg-dark :slant italic)))

   ;; --- mu4e ----------------------------------------------------------
   `(mu4e-title-face ((,class :foreground ,accent :weight bold)))
   `(mu4e-header-face ((,class :foreground ,fg)))
   `(mu4e-header-title-face ((,class :foreground ,accent)))
   `(mu4e-header-highlight-face ((,class :background ,select :foreground ,fg-bright :weight bold :extend t)))
   `(mu4e-header-key-face ((,class :foreground ,accent :weight bold)))
   `(mu4e-header-value-face ((,class :foreground ,fg)))
   `(mu4e-header-marks-face ((,class :foreground ,yellow)))
   `(mu4e-special-header-value-face ((,class :foreground ,cyan)))
   `(mu4e-unread-face ((,class :foreground ,accent :weight bold)))
   `(mu4e-flagged-face ((,class :foreground ,yellow :weight bold)))
   `(mu4e-replied-face ((,class :foreground ,fn)))
   `(mu4e-forwarded-face ((,class :foreground ,bmagenta)))
   `(mu4e-draft-face ((,class :foreground ,orange :slant italic)))
   `(mu4e-trashed-face ((,class :foreground ,fg-dark :strike-through t)))
   `(mu4e-related-face ((,class :foreground ,fg-dark)))
   `(mu4e-highlight-face ((,class :foreground ,accent :weight bold)))
   `(mu4e-link-face ((,class :foreground ,blue :underline t)))
   `(mu4e-contact-face ((,class :foreground ,cyan)))
   `(mu4e-modeline-face ((,class :foreground ,accent)))
   `(mu4e-footer-face ((,class :foreground ,fg-dark)))
   `(mu4e-system-face ((,class :foreground ,fg-dark :slant italic)))
   `(mu4e-ok-face ((,class :foreground ,green :weight bold)))
   `(mu4e-warning-face ((,class :foreground ,yellow :weight bold)))
   `(mu4e-compose-separator-face ((,class :foreground ,muted)))
   `(mu4e-region-code ((,class :background ,bg-alt)))
   `(mu4e-context-face ((,class :foreground ,cyan)))
   `(mu4e-thread-fold-face ((,class :foreground ,muted)))

   ;; --- Dired / diredfl -----------------------------------------------
   `(dired-directory ((,class :foreground ,accent :weight bold)))
   `(dired-symlink ((,class :foreground ,cyan :slant italic)))
   `(dired-marked ((,class :foreground ,yellow :weight bold)))
   `(dired-flagged ((,class :foreground ,red :weight bold)))
   `(dired-broken-symlink ((,class :foreground ,red :strike-through t)))
   `(dired-perm-write ((,class :foreground ,orange)))
   `(dired-warning ((,class :foreground ,yellow :weight bold)))
   `(dired-header ((,class :foreground ,accent :weight bold)))
   `(dired-ignored ((,class :foreground ,fg-dark)))
   `(dired-special ((,class :foreground ,bmagenta)))
   `(diredfl-dir-name ((,class :foreground ,accent :weight bold)))
   `(diredfl-dir-heading ((,class :foreground ,accent :weight bold)))
   `(diredfl-file-name ((,class :foreground ,fg)))
   `(diredfl-file-suffix ((,class :foreground ,fg-dark)))
   `(diredfl-date-time ((,class :foreground ,fn)))
   `(diredfl-number ((,class :foreground ,orange)))
   `(diredfl-symlink ((,class :foreground ,cyan)))
   `(diredfl-compressed-file-name ((,class :foreground ,yellow)))
   `(diredfl-compressed-file-suffix ((,class :foreground ,yellow)))
   `(diredfl-flag-mark ((,class :foreground ,yellow :weight bold)))
   `(diredfl-flag-mark-line ((,class :background ,select)))
   `(diredfl-deletion ((,class :foreground ,red :weight bold)))
   `(diredfl-deletion-file-name ((,class :foreground ,red :strike-through t)))
   `(diredfl-ignored-file-name ((,class :foreground ,fg-dark)))
   `(diredfl-exec-priv ((,class :foreground ,green)))
   `(diredfl-read-priv ((,class :foreground ,yellow)))
   `(diredfl-write-priv ((,class :foreground ,red)))
   `(diredfl-no-priv ((,class :foreground ,muted)))
   `(diredfl-dir-priv ((,class :foreground ,accent)))
   `(diredfl-link-priv ((,class :foreground ,cyan)))
   `(diredfl-rare-priv ((,class :foreground ,bmagenta)))
   `(diredfl-other-priv ((,class :foreground ,orange)))
   `(diredfl-executable-tag ((,class :foreground ,green)))

   ;; --- Eglot / Flymake ----------------------------------------------
   `(eglot-highlight-symbol-face ((,class :background ,select :underline t)))
   `(eglot-mode-line ((,class :foreground ,accent :weight bold)))
   `(eglot-diagnostic-tag-unnecessary-face ((,class :foreground ,fg-dark :strike-through t)))
   `(eglot-diagnostic-tag-deprecated-face ((,class :foreground ,fg-dark :strike-through t)))
   `(eglot-inlay-hint-face ((,class :foreground ,muted :slant italic :height 0.9)))
   `(eglot-type-hint-face ((,class :inherit eglot-inlay-hint-face :foreground ,type)))
   `(eglot-parameter-hint-face ((,class :inherit eglot-inlay-hint-face :foreground ,cyan)))
   `(flymake-error ((,class :underline (:style wave :color ,red))))
   `(flymake-warning ((,class :underline (:style wave :color ,yellow))))
   `(flymake-note ((,class :underline (:style wave :color ,cyan))))
   `(flymake-error-echo ((,class :foreground ,red :weight bold)))
   `(flymake-warning-echo ((,class :foreground ,yellow :weight bold)))
   `(flymake-note-echo ((,class :foreground ,cyan)))

   ;; --- ERC -----------------------------------------------------------
   `(erc-default-face ((,class :foreground ,fg)))
   `(erc-nick-default-face ((,class :foreground ,accent :weight bold)))
   `(erc-my-nick-face ((,class :foreground ,cyan :weight bold)))
   `(erc-current-nick-face ((,class :foreground ,yellow :weight bold)))
   `(erc-input-face ((,class :foreground ,fg-light)))
   `(erc-timestamp-face ((,class :foreground ,fg-dark)))
   `(erc-notice-face ((,class :foreground ,muted)))
   `(erc-prompt-face ((,class :foreground ,accent :weight bold)))
   `(erc-direct-msg-face ((,class :foreground ,orange)))
   `(erc-error-face ((,class :foreground ,red :weight bold)))
   `(erc-keyword-face ((,class :foreground ,yellow :weight bold)))
   `(erc-button ((,class :foreground ,blue :underline t)))
   `(erc-nick-msg-face ((,class :foreground ,bgreen)))
   `(erc-dangerous-host-face ((,class :foreground ,red)))
   `(erc-pal-face ((,class :foreground ,bmagenta)))

   ;; --- Term / vterm / ANSI ------------------------------------------
   `(term ((,class :background ,bg :foreground ,fg)))
   `(term-color-black ((,class :background ,bg :foreground ,muted)))
   `(term-color-red ((,class :background ,red :foreground ,red)))
   `(term-color-green ((,class :background ,green :foreground ,green)))
   `(term-color-yellow ((,class :background ,yellow :foreground ,yellow)))
   `(term-color-blue ((,class :background ,blue :foreground ,blue)))
   `(term-color-magenta ((,class :background ,magenta :foreground ,magenta)))
   `(term-color-cyan ((,class :background ,cyan :foreground ,cyan)))
   `(term-color-white ((,class :background ,fg :foreground ,fg)))
   `(term-color-bright-black ((,class :background ,muted :foreground ,muted)))
   `(term-color-bright-red ((,class :background ,bred :foreground ,bred)))
   `(term-color-bright-green ((,class :background ,bgreen :foreground ,bgreen)))
   `(term-color-bright-yellow ((,class :background ,byellow :foreground ,byellow)))
   `(term-color-bright-blue ((,class :background ,bblue :foreground ,bblue)))
   `(term-color-bright-magenta ((,class :background ,bmagenta :foreground ,bmagenta)))
   `(term-color-bright-cyan ((,class :background ,bcyan :foreground ,bcyan)))
   `(term-color-bright-white ((,class :background ,fg-bright :foreground ,fg-bright)))
   `(ansi-color-black ((,class :background ,bg :foreground ,bg)))
   `(ansi-color-red ((,class :background ,red :foreground ,red)))
   `(ansi-color-green ((,class :background ,green :foreground ,green)))
   `(ansi-color-yellow ((,class :background ,yellow :foreground ,yellow)))
   `(ansi-color-blue ((,class :background ,blue :foreground ,blue)))
   `(ansi-color-magenta ((,class :background ,magenta :foreground ,magenta)))
   `(ansi-color-cyan ((,class :background ,cyan :foreground ,cyan)))
   `(ansi-color-white ((,class :background ,fg :foreground ,fg)))
   `(ansi-color-bright-black ((,class :background ,muted :foreground ,muted)))
   `(ansi-color-bright-red ((,class :background ,bred :foreground ,bred)))
   `(ansi-color-bright-green ((,class :background ,bgreen :foreground ,bgreen)))
   `(ansi-color-bright-yellow ((,class :background ,byellow :foreground ,byellow)))
   `(ansi-color-bright-blue ((,class :background ,bblue :foreground ,bblue)))
   `(ansi-color-bright-magenta ((,class :background ,bmagenta :foreground ,bmagenta)))
   `(ansi-color-bright-cyan ((,class :background ,bcyan :foreground ,bcyan)))
   `(ansi-color-bright-white ((,class :background ,fg-bright :foreground ,fg-bright)))
   `(vterm-color-black ((,class :background ,bg :foreground ,muted)))
   `(vterm-color-red ((,class :background ,red :foreground ,red)))
   `(vterm-color-green ((,class :background ,green :foreground ,green)))
   `(vterm-color-yellow ((,class :background ,yellow :foreground ,yellow)))
   `(vterm-color-blue ((,class :background ,blue :foreground ,blue)))
   `(vterm-color-magenta ((,class :background ,magenta :foreground ,magenta)))
   `(vterm-color-cyan ((,class :background ,cyan :foreground ,cyan)))
   `(vterm-color-white ((,class :background ,fg :foreground ,fg)))
   `(vterm-color-bright-black ((,class :background ,muted :foreground ,muted)))
   `(vterm-color-bright-red ((,class :background ,bred :foreground ,bred)))
   `(vterm-color-bright-green ((,class :background ,bgreen :foreground ,bgreen)))
   `(vterm-color-bright-yellow ((,class :background ,byellow :foreground ,byellow)))
   `(vterm-color-bright-blue ((,class :background ,bblue :foreground ,bblue)))
   `(vterm-color-bright-magenta ((,class :background ,bmagenta :foreground ,bmagenta)))
   `(vterm-color-bright-cyan ((,class :background ,bcyan :foreground ,bcyan)))
   `(vterm-color-bright-white ((,class :background ,fg-bright :foreground ,fg-bright)))
   `(vterm-color-underline ((,class :underline t)))
   `(vterm-color-inverse-video ((,class :inverse-video t)))
   `(eshell-prompt ((,class :foreground ,accent :weight bold)))
   `(eshell-ls-directory ((,class :foreground ,accent :weight bold)))
   `(eshell-ls-symlink ((,class :foreground ,cyan)))
   `(eshell-ls-executable ((,class :foreground ,green :weight bold)))
   `(eshell-ls-archive ((,class :foreground ,yellow)))
   `(eshell-ls-backup ((,class :foreground ,fg-dark)))
   `(eshell-ls-clutter ((,class :foreground ,fg-dark)))
   `(eshell-ls-missing ((,class :foreground ,red :weight bold)))
   `(eshell-ls-product ((,class :foreground ,orange)))
   `(eshell-ls-readonly ((,class :foreground ,yellow)))
   `(eshell-ls-special ((,class :foreground ,bmagenta)))
   `(eshell-ls-unreadable ((,class :foreground ,red)))

   ;; --- Markdown ------------------------------------------------------
   `(markdown-header-face-1 ((,class :foreground ,accent :weight bold :height 1.3)))
   `(markdown-header-face-2 ((,class :foreground ,bgreen :weight bold :height 1.2)))
   `(markdown-header-face-3 ((,class :foreground ,yellow :weight bold :height 1.1)))
   `(markdown-header-face-4 ((,class :foreground ,cyan :weight bold)))
   `(markdown-header-face-5 ((,class :foreground ,bblue :weight bold)))
   `(markdown-header-face-6 ((,class :foreground ,bmagenta :weight bold)))
   `(markdown-code-face ((,class :foreground ,cyan :background ,bg-alt :extend t)))
   `(markdown-inline-code-face ((,class :foreground ,cyan :background ,bg-alt)))
   `(markdown-link-face ((,class :foreground ,blue :underline t)))
   `(markdown-url-face ((,class :foreground ,fn :underline t)))
   `(markdown-blockquote-face ((,class :foreground ,fg-light :slant italic)))
   `(markdown-language-keyword-face ((,class :foreground ,keyword)))
   `(markdown-pre-face ((,class :foreground ,cyan)))
   `(markdown-table-face ((,class :foreground ,fg-light)))

   ;; --- Widgets / Custom / buttons -----------------------------------
   `(widget-field ((,class :background ,bg-alt :foreground ,fg :box (:line-width 1 :color ,muted))))
   `(widget-button ((,class :foreground ,accent :weight bold)))
   `(widget-button-pressed ((,class :foreground ,green :weight bold)))
   `(widget-inactive ((,class :foreground ,fg-dark)))
   `(widget-single-line-field ((,class :inherit widget-field)))
   `(custom-button
     ((,class :background ,select :foreground ,accent
              :box (:line-width 1 :color ,accent :style released-button))))
   `(custom-button-mouse
     ((,class :background ,accent :foreground ,bg
              :box (:line-width 1 :color ,accent :style released-button))))
   `(custom-button-pressed
     ((,class :background ,bg :foreground ,accent
              :box (:line-width 1 :color ,accent :style pressed-button))))
   `(custom-group-tag ((,class :foreground ,accent :weight bold :height 1.2)))
   `(custom-variable-tag ((,class :foreground ,cyan :weight bold)))
   `(custom-state ((,class :foreground ,green)))
   `(custom-changed ((,class :foreground ,yellow)))
   `(custom-invalid ((,class :foreground ,red :weight bold)))
   `(custom-comment ((,class :foreground ,comment :slant italic)))
   `(custom-documentation ((,class :foreground ,fg)))

   ;; --- Transient / Magit popups / which-key --------------------------
   `(transient-heading ((,class :foreground ,accent :weight bold)))
   `(transient-key ((,class :foreground ,accent :weight bold)))
   `(transient-key-stay ((,class :foreground ,green :weight bold)))
   `(transient-key-exit ((,class :foreground ,red :weight bold)))
   `(transient-key-return ((,class :foreground ,yellow :weight bold)))
   `(transient-key-noop ((,class :foreground ,fg-dark)))
   `(transient-key-recurse ((,class :foreground ,fn :weight bold)))
   `(transient-key-stack ((,class :foreground ,bblue :weight bold)))
   `(transient-argument ((,class :foreground ,cyan :weight bold)))
   `(transient-value ((,class :foreground ,green)))
   `(transient-inactive-argument ((,class :foreground ,fg-dark)))
   `(transient-inactive-value ((,class :foreground ,fg-dark)))
   `(transient-unreachable ((,class :foreground ,muted)))
   `(which-key-key-face ((,class :foreground ,accent :weight bold)))
   `(which-key-separator-face ((,class :foreground ,muted)))
   `(which-key-command-description-face ((,class :foreground ,fg)))
   `(which-key-group-description-face ((,class :foreground ,cyan)))
   `(which-key-local-map-description-face ((,class :foreground ,yellow)))
   `(which-key-highlighted-command-face ((,class :foreground ,yellow :weight bold)))

   ;; --- Misc packages -------------------------------------------------
   `(avy-lead-face ((,class :background ,accent :foreground ,bg :weight bold)))
   `(avy-lead-face-0 ((,class :background ,cyan :foreground ,bg :weight bold)))
   `(avy-lead-face-1 ((,class :background ,yellow :foreground ,bg :weight bold)))
   `(avy-lead-face-2 ((,class :background ,bblue :foreground ,bg :weight bold)))
   `(pulse-highlight-start-face ((,class :background ,select)))
   `(pulse-highlight-face ((,class :background ,select)))
   `(rainbow-delimiters-depth-1-face ((,class :foreground ,accent)))
   `(rainbow-delimiters-depth-2-face ((,class :foreground ,cyan)))
   `(rainbow-delimiters-depth-3-face ((,class :foreground ,yellow)))
   `(rainbow-delimiters-depth-4-face ((,class :foreground ,bblue)))
   `(rainbow-delimiters-depth-5-face ((,class :foreground ,bgreen)))
   `(rainbow-delimiters-depth-6-face ((,class :foreground ,bmagenta)))
   `(rainbow-delimiters-depth-7-face ((,class :foreground ,orange)))
   `(rainbow-delimiters-depth-8-face ((,class :foreground ,fg-light)))
   `(rainbow-delimiters-depth-9-face ((,class :foreground ,fn)))
   `(rainbow-delimiters-mismatched-face ((,class :foreground ,red :weight bold)))
   `(rainbow-delimiters-unmatched-face ((,class :foreground ,red :weight bold)))
   `(whitespace-space ((,class :foreground ,muted)))
   `(whitespace-tab ((,class :foreground ,muted)))
   `(whitespace-newline ((,class :foreground ,muted)))
   `(whitespace-trailing ((,class :background ,red :foreground ,fg-bright)))
   `(whitespace-line ((,class :background ,bg-alt :foreground ,orange)))
   `(whitespace-empty ((,class :background ,bg-alt)))
   `(whitespace-indentation ((,class :foreground ,muted)))
   `(whitespace-hspace ((,class :foreground ,muted)))
   `(whitespace-big-indent ((,class :background ,select)))
   `(info-title-1 ((,class :foreground ,accent :weight bold :height 1.3)))
   `(info-title-2 ((,class :foreground ,bgreen :weight bold :height 1.2)))
   `(info-title-3 ((,class :foreground ,yellow :weight bold)))
   `(info-title-4 ((,class :foreground ,cyan :weight bold)))
   `(info-menu-star ((,class :foreground ,accent)))
   `(info-header-node ((,class :foreground ,fg-light :weight bold)))
   `(info-node ((,class :foreground ,accent :weight bold)))
   `(info-xref ((,class :foreground ,blue :underline t)))
   `(info-xref-visited ((,class :foreground ,bmagenta :underline t)))
   `(dictionary-word-definition-face ((,class :foreground ,fg)))
   `(dictionary-word-entry-face ((,class :foreground ,accent :weight bold)))
   `(dictionary-reference-face ((,class :foreground ,blue :underline t)))
   `(elfeed-log-error-level-face ((,class :foreground ,red)))
   `(elfeed-log-warn-level-face ((,class :foreground ,yellow)))
   `(elfeed-log-info-level-face ((,class :foreground ,cyan)))
   `(elfeed-log-debug-level-face ((,class :foreground ,fg-dark)))
   `(elfeed-log-date-face ((,class :foreground ,fg-dark)))
   `(all-the-icons-red ((,class :foreground ,red)))
   `(all-the-icons-green ((,class :foreground ,green)))
   `(all-the-icons-yellow ((,class :foreground ,yellow)))
   `(all-the-icons-blue ((,class :foreground ,blue)))
   `(all-the-icons-maroon ((,class :foreground ,magenta)))
   `(all-the-icons-purple ((,class :foreground ,bmagenta)))
   `(all-the-icons-orange ((,class :foreground ,orange)))
   `(all-the-icons-cyan ((,class :foreground ,cyan)))
   `(all-the-icons-dgreen ((,class :foreground ,fg-dark)))
   `(all-the-icons-lgreen ((,class :foreground ,bgreen)))
   `(package-name ((,class :foreground ,cyan :underline t)))
   `(package-description ((,class :foreground ,fg)))
   `(package-status-available ((,class :foreground ,green)))
   `(package-status-installed ((,class :foreground ,accent :weight bold)))
   `(package-status-dependency ((,class :foreground ,fn)))
   `(package-status-incompat ((,class :foreground ,red)))
   `(package-status-built-in ((,class :foreground ,fg-dark)))
   `(icomplete-section ((,class :foreground ,accent :slant italic)))
   `(calendar-today ((,class :foreground ,accent :weight bold :underline t)))
   `(calendar-weekday-header ((,class :foreground ,fg)))
   `(calendar-weekend-header ((,class :foreground ,fg-dark)))
   `(calendar-month-header ((,class :foreground ,accent :weight bold)))
   `(holiday ((,class :foreground ,red)))
   `(diary ((,class :foreground ,yellow)))
   `(outline-1 ((,class :inherit org-level-1)))
   `(outline-2 ((,class :inherit org-level-2)))
   `(outline-3 ((,class :inherit org-level-3)))
   `(outline-4 ((,class :inherit org-level-4)))
   `(outline-5 ((,class :inherit org-level-5)))
   `(outline-6 ((,class :inherit org-level-6)))
   `(outline-7 ((,class :inherit org-level-7)))
   `(outline-8 ((,class :inherit org-level-8)))
   `(shr-link ((,class :foreground ,blue :underline t)))
   `(shr-selected-link ((,class :background ,select :foreground ,accent)))
   `(shr-h1 ((,class :foreground ,accent :weight bold :height 1.3)))
   `(shr-h2 ((,class :foreground ,bgreen :weight bold)))
   `(shr-h3 ((,class :foreground ,yellow :weight bold)))
   `(eww-form-submit ((,class :background ,select :foreground ,accent)))
   `(eww-form-text ((,class :background ,bg-alt :foreground ,fg :box (:line-width 1 :color ,muted))))
   `(Man-overstrike ((,class :foreground ,accent :weight bold)))
   `(Man-underline ((,class :foreground ,cyan :underline t)))
   `(woman-bold ((,class :foreground ,accent :weight bold)))
   `(woman-italic ((,class :foreground ,cyan :slant italic)))
   `(compilation-error ((,class :foreground ,red :weight bold)))
   `(compilation-warning ((,class :foreground ,yellow :weight bold)))
   `(compilation-info ((,class :foreground ,green)))
   `(compilation-line-number ((,class :foreground ,fn)))
   `(compilation-column-number ((,class :foreground ,fg-dark)))
   `(compilation-mode-line-fail ((,class :foreground ,red :weight bold)))
   `(compilation-mode-line-exit ((,class :foreground ,green :weight bold)))
   `(compilation-mode-line-run ((,class :foreground ,yellow)))
   `(flyspell-incorrect ((,class :underline (:style wave :color ,red))))
   `(flyspell-duplicate ((,class :underline (:style wave :color ,yellow))))
   `(tty-menu-enabled-face ((,class :background ,bg-alt :foreground ,fg)))
   `(tty-menu-disabled-face ((,class :background ,bg-alt :foreground ,fg-dark)))
   `(tty-menu-selected-face ((,class :background ,select :foreground ,accent :weight bold)))
   `(hi-yellow ((,class :background ,yellow :foreground ,bg)))
   `(hi-green ((,class :background ,green :foreground ,bg)))
   `(hi-blue ((,class :background ,blue :foreground ,fg-bright)))
   `(hi-pink ((,class :background ,bmagenta :foreground ,bg)))
   `(hi-red-b ((,class :foreground ,red :weight bold)))
   `(hi-green-b ((,class :foreground ,green :weight bold)))
   `(hi-blue-b ((,class :foreground ,bblue :weight bold)))
   `(hi-salmon ((,class :background ,orange :foreground ,bg)))
   `(hi-aquamarine ((,class :background ,cyan :foreground ,bg)))
   `(bookmark-face ((,class :foreground ,accent)))
   `(bookmark-menu-heading ((,class :foreground ,accent :weight bold)))
   `(pdf-view-region ((,class :inherit region)))
   `(comint-highlight-prompt ((,class :foreground ,accent :weight bold)))
   `(comint-highlight-input ((,class :foreground ,fg-light)))
   `(eldoc-highlight-function-argument ((,class :foreground ,accent :weight bold)))
   `(elisp-shorthand-font-lock-face ((,class :foreground ,cyan)))
   `(help-argument-name ((,class :foreground ,cyan :slant italic)))
   `(apropos-symbol ((,class :foreground ,accent :weight bold)))
   `(apropos-function-button ((,class :foreground ,fn :underline t)))
   `(apropos-variable-button ((,class :foreground ,cyan :underline t)))
   `(apropos-misc-button ((,class :foreground ,yellow :underline t)))
   `(cape-annotation ((,class :foreground ,fg-dark :slant italic)))
   `(popwin-mode-line-inactive ((,class :inherit mode-line-inactive)))
   `(ollama-buddy-prompt-face ((,class :foreground ,accent :weight bold))))

  (custom-theme-set-variables
   'omarchy-matrix
   '(frame-background-mode 'dark)
   `(ansi-color-names-vector
     [,bg ,red ,green ,yellow ,blue ,magenta ,cyan ,fg])))

;;;###autoload
(when (and (boundp 'custom-theme-load-path) load-file-name)
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'omarchy-matrix)
;;; omarchy-matrix-theme.el ends here
